name: docs

on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.2
      - name: setup node
        with:
          node-version: 12.x
      - name: build
        run: npx docsify-cli build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{secrets.GP_TOKEN}}
          BRANCH: gh-pages
          FOLDER: docs
